# Generated by Django 5.0 on 2026-01-22 10:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.CharField(blank=True, default='fa-folder', help_text='Font Awesome icon class', max_length=50)),
                ('color', models.CharField(default='#FF6B01', help_text='Category color (hex code)', max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Is this category currently active?')),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vendor/Company name', max_length=200)),
                ('contact_person', models.CharField(blank=True, help_text='Primary contact person', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(blank=True, help_text='Vendor address')),
                ('gst_number', models.CharField(blank=True, help_text='GST/Tax registration number', max_length=50)),
                ('bank_details', models.TextField(blank=True, help_text='Bank account details for payments')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vendor')),
                ('is_active', models.BooleanField(default=True, help_text='Is this vendor currently active?')),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin (IT/Finance Head)'), ('executive', 'IT Executive'), ('manager', 'Manager/Accounts (Read-only)')], default='executive', help_text='User role determines access permissions', max_length=20)),
                ('department', models.CharField(blank=True, default='IT', help_text='Department the user belongs to', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag - never lose data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=12)),
                ('date', models.DateField(help_text='Date of expense')),
                ('description', models.TextField(help_text='Description of the expense')),
                ('purpose', models.CharField(blank=True, help_text='Purpose or project for this expense', max_length=300)),
                ('invoice_number', models.CharField(blank=True, help_text='Invoice/Bill number', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, help_text='Date and time of approval', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Expense category', on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.category')),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Bill/Invoice file (PDF, JPG, PNG)', upload_to='bills/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('description', models.CharField(blank=True, help_text='Bill description', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(help_text='Related expense', on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.expense')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this bill', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Bill',
                'verbose_name_plural': 'Expense Bills',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('company', 'Company Accounts Department'), ('manager', 'Manager Advance'), ('personal', 'Employee Personal Money'), ('refund', 'Vendor Refund'), ('other', 'Other')], help_text='Source of the income', max_length=20)),
                ('source_detail', models.CharField(blank=True, help_text='Additional details about the source (e.g., person name)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount received', max_digits=12)),
                ('date', models.DateField(help_text='Date of receiving the amount')),
                ('reference_number', models.CharField(blank=True, help_text='Reference number (voucher, transaction ID, etc.)', max_length=100)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('online', 'Online Payment'), ('cheque', 'Cheque')], default='cash', help_text='Mode of payment', max_length=20)),
                ('project', models.CharField(blank=True, help_text='Linked project or purpose (optional)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description or notes about this income')),
                ('is_reimbursable', models.BooleanField(default=False, help_text='Is this amount to be reimbursed later?')),
                ('reimbursed', models.BooleanField(default=False, help_text='Has this amount been reimbursed?')),
                ('reimbursed_date', models.DateField(blank=True, help_text='Date when reimbursement was received', null=True)),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this record', on_delete=django.db.models.deletion.PROTECT, related_name='incomes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_income',
            field=models.ForeignKey(blank=True, help_text='Income source for this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expenses', to='core.income'),
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ledger name (e.g., "My Personal Fund", "Manager Advance")', max_length=100)),
                ('ledger_type', models.CharField(choices=[('personal', 'Personal Money'), ('manager', 'Manager Advance'), ('employee', 'Employee Advance')], default='personal', help_text='Type of ledger', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this ledger')),
                ('is_active', models.BooleanField(default=True, help_text='Is this ledger currently active?')),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Owner of this ledger', on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledgers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('advance', 'Advance Received'), ('expense', 'Expense Made'), ('reimbursement', 'Reimbursement Received'), ('return', 'Amount Returned')], help_text='Type of entry', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Entry amount', max_digits=12)),
                ('date', models.DateField(help_text='Date of entry')),
                ('description', models.TextField(help_text='Description of this entry')),
                ('reference', models.CharField(blank=True, help_text='Reference number or linked transaction', max_length=100)),
                ('is_soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this entry', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(help_text='Related ledger', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.ledger')),
                ('linked_expense', models.ForeignKey(blank=True, help_text='Linked expense (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.expense')),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor/Supplier', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, help_text='Username at time of action (preserved even if user deleted)', max_length=150)),
                ('user_role', models.CharField(blank=True, help_text='User role at time of action', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('soft_delete', 'Soft Delete'), ('restore', 'Restore'), ('view', 'View'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text='Name of the affected model', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the affected record', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=300)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values (for updates)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values (for creates/updates)', null=True)),
                ('changes_summary', models.TextField(blank=True, help_text='Human-readable summary of changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/Client user agent')),
                ('request_path', models.CharField(blank=True, help_text='Request URL path', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx'), models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['action', 'timestamp'], name='core_auditl_action_096de0_idx'), models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx')],
            },
        ),
    ]
