# Generated by Django 5.0 on 2026-01-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incomesource_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerentry',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='linked_expense',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (IT/Finance Head)'), ('executive', 'IT Executive'), ('manager', 'Manager/Accounts'), ('user', 'Simple User (View Only)')], default='user', help_text='User role determines access permissions', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='LedgerEntry',
        ),
    ]
