# Generated by Django 5.0 on 2026-01-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_simple_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bill name (e.g., Internet, Hosting)', max_length=200)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Standard billing amount', max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', help_text='Billing frequency', max_length=20)),
                ('billing_day', models.PositiveIntegerField(default=1, help_text='Day of month bill is due (1-28)')),
                ('start_date', models.DateField(help_text='When this recurring bill started')),
                ('description', models.TextField(blank=True, help_text='Additional details')),
                ('is_active', models.BooleanField(default=True, help_text='Is this bill still active')),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Expense category', on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='core.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills_created', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, help_text='Service provider', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recurring_bills', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Recurring Bill',
                'verbose_name_plural': 'Recurring Bills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Billing period start')),
                ('period_end', models.DateField(help_text='Billing period end')),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount for this period', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, help_text='Date payment was made', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_payments_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.OneToOneField(blank=True, help_text='Linked expense record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payment', to='core.expense')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.recurringbill')),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'ordering': ['-due_date'],
            },
        ),
    ]
