# Generated by Django 5.0 on 2026-02-09 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurringbill_billpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Role name (e.g., Admin, Manager, Viewer)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this role')),
                ('can_view', models.BooleanField(default=True, help_text='Can view records')),
                ('can_create', models.BooleanField(default=False, help_text='Can create new records')),
                ('can_edit', models.BooleanField(default=False, help_text='Can edit existing records')),
                ('can_delete', models.BooleanField(default=False, help_text='Can delete records (soft delete)')),
                ('can_approve', models.BooleanField(default=False, help_text='Can approve/reject expenses')),
                ('can_manage_income', models.BooleanField(default=False, help_text='Can manage income records')),
                ('can_manage_expenses', models.BooleanField(default=False, help_text='Can manage expense records')),
                ('can_manage_vendors', models.BooleanField(default=False, help_text='Can manage vendors')),
                ('can_manage_categories', models.BooleanField(default=False, help_text='Can manage categories')),
                ('can_manage_recurring_bills', models.BooleanField(default=False, help_text='Can manage recurring bills')),
                ('can_manage_income_sources', models.BooleanField(default=False, help_text='Can manage income sources')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Can view reports dashboard')),
                ('can_view_expense_report', models.BooleanField(default=False, help_text='Can view monthly expense report')),
                ('can_view_income_report', models.BooleanField(default=False, help_text='Can view income vs expense report')),
                ('can_view_account_balance', models.BooleanField(default=False, help_text='Can view account balance report')),
                ('can_view_reimbursement_report', models.BooleanField(default=False, help_text='Can view reimbursement report')),
                ('can_view_audit_trail', models.BooleanField(default=False, help_text='Can view audit trail')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export data to Excel')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage user accounts')),
                ('can_manage_roles', models.BooleanField(default=False, help_text='Can manage roles and permissions')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role active?')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default role for new users?')),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin (IT/Finance Head)'), ('executive', 'IT Executive'), ('manager', 'Manager/Accounts'), ('user', 'Simple User (View Only)')], default='user', help_text='Legacy role (use user_role for dynamic permissions)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(blank=True, help_text='Dynamic role with customizable permissions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role'),
        ),
    ]
