# Generated by Django 5.0 on 2026-02-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_role_alter_user_role_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('executive', 'IT Executive'), ('accountant', 'Accountant'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', help_text='User role determines access permissions', max_length=20),
        ),
    ]
