# Generated by Django 5.0 on 2026-02-09 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_user_role_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='linked_income',
            field=models.ForeignKey(blank=True, help_text='Income source for this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='core.income'),
        ),
        migrations.AddField(
            model_name='billpayment',
            name='payment_type',
            field=models.CharField(choices=[('it_payment', 'IT Payment (from IT Budget)'), ('accounts_pay', 'Accounts Direct Pay (to Vendor)')], default='it_payment', help_text='Who handles the payment', max_length=20),
        ),
    ]
